// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ViewMyProfileTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void viewMyProfile() {
    driver.get("https://www.facebook.com/?_rdc=1&_rdr");
    driver.manage().window().setSize(new Dimension(1382, 744));
    {
      WebElement element = driver.findElement(By.cssSelector(".x78zum5 > .x1i10hfl > .x1rg5ohu image"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".x78zum5 > .x1i10hfl > .x1rg5ohu .xbh8q5q"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".x78zum5 > .x1i10hfl > .x1rg5ohu g")).click();
    driver.findElement(By.cssSelector(".x9f619 > .x78zum5 > .x9f619 > .x1i10hfl > .x9f619 > .x9f619 > .x193iq5w")).click();
    js.executeScript("window.scrollTo(0,206)");
    js.executeScript("window.scrollTo(0,221)");
    {
      WebElement element = driver.findElement(By.cssSelector(".x1n2onr6:nth-child(1) > .x1n2onr6 > .x1i10hfl > .x6s0dn4 .xqtp20y .x1ey2m1c"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
